JVSafaris/JVSafaris/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings  
from django.conf.urls.static import static  
urlpatterns = [
    path('',include('JVSafarisMain.urls')),
    path('JVSafarisMain/',include('JVSafarisMain.urls')),
    path('blogs/',include('blogs.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)  

JVSafaris/JVSafarisMain/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'JVS'
urlpatterns = [
    path('',views.index,name = 'index'),
    path('packages/',views.packages,name = 'packages'),
    path('packages/description/<package>',views.package_desc,name = 'package-desc'),
    path('services/',views.services_Categories,name = 'services'),
    path('about/',views.about,name = 'about'),

    path('testimonials/',views.testimonials,name = 'testimonials'),
    path('testimonials/new-testimonial',views.new_testimonial_page,name = 'new-testimonial'),


    path('guides/',views.guide,name='guides'),
    path('contact/',views.contact,name = 'contact'),
    path('about/',views.about,name = 'about'),
    path('destinations/',views.destinations,name = 'destinations'),

    path('package/booking/<int:id>',views.booking,name = 'booking'),
    path('package/booking/payment/<id>',views.payment,name = 'payments'),

    path('services/<int:id>',views.services,name = 'service-items'),
    path('service/booking/<int:id>',views.service_booking,name = 'service-booking'  ),
    path('service/booking/payment/<int:id>',views.service_payment,name = 'service-payment'),
    path('service/details/<int:id>',views.service_details,name = 'service-detail'),

    path('auth/login/',views._login,name = 'login'),
    path('auth/sign-up/',views.sign_up,name = 'sign_up'),
    path('auth/logout/',views.logout_view,name = 'logout'),
    path('auth/login-required/',views.required,name = 'login-required'),

    path('newsletter/',views.newsletter,name = 'newsletter'),

    path('myaccount/',views.myAccount,name = 'myAccount')


]

JVSafaris/blogs/urls.py
from django.urls import path
from . import views

app_name = 'JVSBlogs'
urlpatterns = [
        path('',views.index,name = 'index'),
        path('details/<int:id>',views.details,name = 'details'),
        path('blog-categories/<category>',views.category,name = 'category'),

        path('comment/<int:id>',views.comment,name = 'comment')

]

JVSafaris/JVSafarisMain/models.py
from email.policy import default
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class ServiceCategory(models.Model):
    category_name = models.CharField(max_length=400)
    category_description = models.CharField(max_length=400)

    def __str__(self):
        return self.category_name

class Service(models.Model):
    category = models.ForeignKey(ServiceCategory,on_delete = models.CASCADE)
    category_description = models.CharField(max_length=1000)

    def __str__(self):
        return self.category_description

class ServiceItem(models.Model):
    category = models.ForeignKey(ServiceCategory,on_delete= models.CASCADE)
    service = models.ForeignKey(Service,on_delete=models.CASCADE)
    item_description = models.CharField(max_length=400)
    optional = models.BooleanField()
   # price = models.FloatField(default=0.0)
    desc = models.CharField(max_length=4000,default='')
    location = models.CharField(max_length=200,default='')
    image = models.FileField(default = '')
    start_date = models.DateField(default=timezone.now)
    end_date = models.DateField(default=timezone.now)
    duration = models.IntegerField(default=2)
    adults = models.IntegerField(default=2)
    kids = models.IntegerField(default=0)


    def __str__(self):
        return self.item_description

    def price(self):
        cost = self.servicechargecharter_set.order_by('-id').first()
        return cost


class ServiceItemGallery(models.Model):
    service_item = models.ForeignKey(ServiceItem,on_delete = models.CASCADE)
    image = models.FileField(default = '')

class Destination(models.Model):
    destinantion_name = models.CharField(max_length = 400)
    image = models.FileField(default = '')

    def __str__(self):
        return self.destinantion_name
   

class ServiceChargeCharter(models.Model):
    service = models.ForeignKey(ServiceItem,on_delete=models.CASCADE)
    charge = models.IntegerField()
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return self.service.item_description

    


class PackageCategory(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=1200)

    def __str__(self):
        return self.name


class Package(models.Model):
    package_name = models.CharField(max_length=400)
    start_date = models.DateField()
    end_date = models.DateField()
    package_desc = models.CharField(max_length=1000)
    image = models.FileField(default = '')
    destination = models.ForeignKey(Destination,on_delete = models.CASCADE,default = 1)
    duration = models.IntegerField(default = 2)
    population = models.IntegerField(default = 2)
    kids = models.IntegerField(default=0)
    category = models.ForeignKey(PackageCategory,on_delete=models.CASCADE)


    def __str__(self):
        return self.package_name

    def price(self):
        cost = self.packagecharter_set.order_by('-id').first()
        return cost

class PackageCharter(models.Model):
    package = models.ForeignKey(Package,on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    charge = models.FloatField()

    def __str__(self):
        return self.package.package_name



class PackageService(models.Model):
    service = models.CharField(max_length = 255)
    package = models.ForeignKey(Package,on_delete = models.CASCADE,default = '')
    is_optional = models.BooleanField(default = True)
    price = models.FloatField(default = 0.0)
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return self.service


class Booking(models.Model):
    fname = models.CharField(max_length = 255)
    lname = models.CharField(max_length = 255)
    adults = models.IntegerField()
    kids = models.IntegerField()
    country = models.CharField(max_length = 255)
    city = models.CharField(max_length = 255)
    email = models.CharField(max_length = 255)
    phone = models.CharField(max_length = 200)
    package = models.ForeignKey(Package,on_delete = models.CASCADE)
    amount = models.FloatField()
    isPaid = models.BooleanField(default = False)

    def __str__(self):
        return str(self.fname) + ' ' + str(self.lname)


class ServiceBooking(models.Model):
    fname = models.CharField(max_length=255)
    lname = models.CharField(max_length = 255)
    adults = models.IntegerField()
    kids = models.IntegerField()
    country = models.CharField(max_length = 255)
    city = models.CharField(max_length = 255)
    email = models.CharField(max_length = 255)
    phone = models.CharField(max_length = 200)
    service = models.ForeignKey(ServiceItem,on_delete = models.CASCADE)
    amount = models.FloatField()
    isPaid = models.BooleanField(default = False)

    def __str__(self):
        return str(self.fname) + ' ' + str(self.lname)

class Staff(models.Model):
    name = models.CharField(max_length=255)
    designation = models.CharField(max_length=255)
    image = models.ImageField()
    twitter = models.CharField(max_length = 1000,blank = True)
    facebook = models.CharField(max_length = 1000,blank=True)
    instagram = models.CharField(max_length = 1000,blank=True)
    linkedin = models.CharField(max_length = 1000,blank = True)
    isEstemeed = models.BooleanField()

    def __str__(self):
        return str(self.name)

class Honeymoon(models.Model):
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    phone = models.CharField(max_length=15)
    destination = models.ForeignKey(Destination,on_delete=models.CASCADE)


    def __str__(self):
        return str(self.name)

class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    subject = models.CharField(max_length=4200)
    message = models.CharField(max_length=4200)
    date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.name

class Newsletter(models.Model):
    email = models.CharField(max_length=255)

    def __str__(self):
        return self.email

class Testimonial(models.Model):
    name = models.CharField(max_length = 255)
    comment = models.CharField(max_length=1200)
    occupation = models.CharField(max_length = 255)
    image = models.ImageField()

    def __str__(self):
        return self.name

JVSafaris/blogs/models.py
from email.policy import default
from django.db import models

#table models
class BlogCategory(models.Model):
    category = models.CharField(max_length = 499)
    description = models.CharField(max_length = 400)

    def __str__(self):
        return self.category
class Author(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=5000)
    facebook = models.CharField(max_length=2000,default='',blank=True)
    twitter = models.CharField(max_length=2000,default='',blank=True)
    linkedin = models.CharField(max_length=2000,default='',blank=True)
    instagram = models.CharField(max_length=2000,default='',blank=True)
    youtube = models.CharField(max_length=2000,default='',blank=True)
    image = models.ImageField()

    def __str__(self):
        return str(self.name)

class Blog(models.Model):
    heading = models.CharField(max_length = 2000)
    image = models.FileField()
    category = models.ForeignKey(BlogCategory,on_delete = models.CASCADE)
    date = models.DateField(auto_now_add=True)
    author = models.ForeignKey(Author,on_delete=models.CASCADE,default=None,null=True)

    def __str__(self):
        return self.heading

class Subheading(models.Model):
    blog = models.ForeignKey(Blog,on_delete = models.CASCADE)
    image = models.FileField()
    sub_heading = models.CharField(max_length = 400)

    def __str__(self):
        return self.sub_heading

class Paragraph(models.Model):
    blog = models.ForeignKey(Blog,on_delete = models.CASCADE)
    heading = models.ForeignKey(Subheading,on_delete = models.CASCADE)
    content = models.CharField(max_length = 10000)
    

    def __str__(self):
        return self.content

class BlogComment(models.Model):
    name = models.CharField(max_length =255)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    message = models.CharField(max_length=4000)
    blog = models.ForeignKey(Blog,on_delete = models.CASCADE)

    def __str__(self):
        return self.name

JVSafaris/blogs/views.py
from django.shortcuts import render,redirect

from .models import *
from JVSafarisMain.models import *
from django.core.paginator import Paginator
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse


# Create your views here.
def index(request):
    page = request.GET.get('page')
    b = Paginator(Blog.objects.order_by('-id').all(),8)
    blogs = b.page(page)
    c = Paginator(BlogCategory.objects.order_by('id').all(),4)
    categories = c.page(1)
    recent = Paginator(Blog.objects.order_by('id').reverse(),4)
    recent_blogs = recent.page(1)
    testimonials = Testimonial.objects.all()
    return render(request,'blogs/blog-home.html',{
        'blogs':blogs,
        'categories':categories,
        'recent_blogs':recent_blogs,
        'testimonials':testimonials
        })

def details(request,id):
    blog = Blog.objects.get(pk = id)
    c = Paginator(BlogCategory.objects.order_by('id').all(),5)
    categories = c.page(1)
    recent = Paginator(Blog.objects.order_by('id').reverse(),4)
    recent_blogs = recent.page(1)
    return render(request,'blogs/blog-detail.html',{'blog':blog,'categories':categories,'recent_blogs':recent_blogs})

def category(request,category):
    c = Paginator(BlogCategory.objects.order_by('id').all(),5)
    categories = c.page(1)
    recent = Paginator(Blog.objects.order_by('id').reverse(),4)
    recent_blogs = recent.page(1)
    cat = BlogCategory.objects.get(pk = category)
    blogs = Blog.objects.filter(category = cat.id).all()
    return render(request,'blogs/blog-home.html',{'blogs':blogs,'categories':categories,'recent_blogs':recent_blogs})

def comment(request,id):
    blog = Blog.objects.get(pk =id)
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        phone = request.POST['phone']
        message = request.POST['message']

        new_comment = BlogComment(name = name,email = email,phone = phone,message = message,blog = blog)
        new_comment.save()
        messages.success(request,'Your comment has saved succesfully')

      
        return HttpResponseRedirect(reverse('JVSBlogs:details',kwargs = {'id':int(id)}))

    else:
        pass


        

JVSafaris/JVSafarisMain/templates/jvsafarismain/account.html
{%extends 'JVSafarisMain/base.html'%}

{%block head%}
{%block pagehead%}
<title>My Account</title>
{%endblock%}
{%endblock%}

{%block pagetitle%}
{%block firsttitle%}
My Account
{%endblock%}
{%endblock%}

{%block subtitle%}
{%block pagesubtitle%}
My Account
{%endblock%}
{%endblock%}


{%block body%}

        {%block content%}


        {%endblock%}

{%endblock%}

JVSafaris/JVSafarisMain/templates/jvsafarismain/booking.html
{%extends 'JVSafarisMain/base.html'%}

{%block head%}
<title>Booking - {{package.package_name}}</title>
{%endblock%}


{%block pagetitle%}
{{package.package_name}}
{%endblock%}


{%block subtitle%}
{{package.package_name}}
{%endblock%}



{%block body%}
<div 
    style="padding: 10px;background-color:white;border:none;box-shadow:2px 4px 5px grey;margin:2% 2%;">
    <form action="{%url 'JVS:booking' package.id%}" method="post">
{%csrf_token%}
        <h5>Please fill the form below to book.</h5>


        <div class="row">
            <div class="col-md-6 col-sm-12">
                <div class="mb-3">
                    <label for="fname" class="form-label">First Name</label>
                    <input name="fname" type="text" class="form-control" id="fname" required>
                </div>

            </div>

            <div class="col-md-6 col-sm-12">
                <div class="mb-3">
                    <label for="lname" class="form-label">Last Name</label>
                    <input name="lname" type="text" class="form-control" id="lname" required>

                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-sm-12">
                <div class="mb-3">
                    <label for="adults" class="form-label">No of adults</label>
                    <input name="adults" type="number" class="form-control" id="adults" required>
                </div>

            </div>

            <div class="col-md-6 col-sm-12">
                <div class="mb-3">
                    <label for="kids" class="form-label">No of kids</label>
                    <input name="kids" type="number" class="form-control" id="kids" required>

                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-sm-12">
                <div class="mb-3">
                    <label for="country" class="form-label">Country</label>
                    <input name="country" type="text" class="form-control" id="country" required>
                </div>

            </div>

            <div class="col-md-6 col-sm-12">
                <div class="mb-3">
                    <label for="city" class="form-label">city</label>
                    <input name="city" type="text" class="form-control" id="city" required>

                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-sm-12">
                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input name="email" type="email" class="form-control" id="email" required>
                </div>

            </div>

            <div class="col-md-6 col-sm-12">
                <div class="mb-3">
                    <label for="phone" class="form-label">Phone number</label>
                    <input name="phone" type="text" class="form-control" id="phone" required>

                </div>
            </div>

            
        

</div>
<button type="submit" class="btn btn-primary col-md-12">Book</button>

    </form>
</div>


{%endblock%}

JVSafaris/JVSafarisMain/templates/jvsafarismain/destination.html
{%extends 'JVSafarisMain/base.html'%}
{%load static%}

{%block head%}
<title>Destinations</title>
{%endblock%}

{%block pagetitle%}
Destinations
{%endblock%}

{%block subtitle%}
Destinations
{%endblock%}

{%block body%}
    <!-- Destination Start -->
    <div class="container-fluid py-5">
        <div class="container pt-5 pb-3">
            <div class="text-center mb-3 pb-3">
                <h6 class="text-primary text-uppercase" style="letter-spacing: 5px;">Destination</h6>
                <h1>Explore Top Destination</h1>
            </div>
            <div class="row">
                {%for destination in destinations%}

                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="destination-item position-relative overflow-hidden mb-2">
                        <img class="img-fluid" src="{{destination.image.url}}" alt="">
                        <a class="destination-overlay text-white text-decoration-none" href="">
                            <h5 class="text-white">{{destination.destinantion_name}}</h5>
                        </a>
                    </div>
                </div>
                {%endfor%}
               
            
             
                
                
            </div>
        </div>
    </div>
    <!-- Destination Start -->

{%endblock%}

JVSafaris/JVSafarisMain/templates/jvsafarismain/new-testimonial.html
{%extends 'JVSafarisMain/base.html'%}

{%block head%}
<title>New Testimonial</title>
{%endblock%}

{%block pagetitle%}
{{name}}
{%endblock%}

{%block subtitle%}
{{name}}
{%endblock%}


{%block body%}

<div class="container-fluid py-5">
    <div class="container py-5">
        <div class="text-center mb-3 pb-3">
            <h6 class="text-primary text-uppercase" style="letter-spacing: 5px;">Testimonial</h6>
            <h1>Enter your Testimonial Below</h1>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="contact-form bg-white" style="padding: 30px;">
                    <div id="success"></div>
                    <form action="{%url 'JVS:testimonials'%}" method="post" enctype="multipart/form-data">
                        {%csrf_token%}
                        <div class="form-row">
                            <div class="control-group col-sm-6">
                                <input type="text" class="form-control p-4" id="name" name="name" placeholder="Your Name"
                                    required="required" data-validation-required-message="Please enter your name" />
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group col-sm-6">
                                <input type="text" class="form-control p-4" name="occupation" placeholder="Please enter your occupation/profession"
                                    required="required" data-validation-required-message="occupation is required" />
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
            
                        <div class="control-group">
                            <textarea name="comment" class="form-control py-3 px-4" rows="5" id="message" placeholder="Your Testimonial..."
                                required="required"
                                data-validation-required-message="Please enter your testimonial"></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group col-sm-6">
                            <input type="file" class="form-control p-4" name="image" "
                                required="required" data-validation-required-message="Please select an image" />
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="text-center">
                            <button class="btn btn-primary py-3 px-4" type="submit" id="sendMessageButton">Send Message</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{%endblock%}

JVSafaris/JVSafarisMain/templates/jvsafarismain/package-detail.html
{%extends 'JVSafarisMain/base.html'%}
{%load static%}

{%block head%}
<title>Package - {{package.package_name}}</title>
{%endblock%}


{%block pagetitle%}
{{package.package_name}}
{%endblock%}

{%block subtitle%}
{{package.package_name}}
{%endblock%}

{%block body%}
<div class="container" style="padding: 10px;">
   <div class="row">
     <div class="col-md-4 col-sm-12">
        <img src="{{package.image.url}}" style="width: 100%;height:100%;" alt="">
     </div>
     <div class="col-md-8 col-sm-6" style="background-color: white;">
        <h2>{{package.package_name}}</h2>
        <div class="row">
            <div class="col-md-5 col-sm-5">

                <p>Validity:<span style="font-weight: 700;">{{package.price.start_date}} - {{package.price.end_date}}</span></p>
                <p>Accommodation:<span style="font-weight: 700;">{{package.population}} adults, {{package.kids}} kids</span> </p>
                <p>Category:<span style="font-weight: 700;">{{package.category.name}}</span></p>

            </div>
            <div class="col-md-6 col-sm-5">
                <p>Duration:<span style="font-weight: 700;">{{package.duration}} days</span></p>
                <p>Destination:<span style="font-weight: 700;">{{package.destination.destinantion_name}}</span></p>
                <p>price:<span style="font-weight: 700;"> Kes {{package.price.charge}}</span></p>
            </div>

        </div>
        <a href="{%url 'JVS:booking' package.id%}"><button class="btn btn-primary" style="width: 100%;margin: 5px;">Book Now</button></a>

    </div>
   </div>

   <div class="row" style="background-color: white;margin: 10px 0 10px 0;padding: 10px;">
    <div class="col-md-6 col-sm-12" >
        <h4>Description</h4>
        <p>
            {{package.package_desc}}
        </p>
    </div>

    <div class="col-md-6 col-sm-12">
        <div class="row">
            <div class="col-md-5 col-sm-6">
                <h6>Inclusives</h6>
                {%for inclusive in package.packageservice_set.all%}
                {%if inclusive.is_optional == False%}
                <p><i style="color: green;" class="fa-solid fa-check"></i> &nbsp;{{inclusive.service}}</p>
                {%endif%}
                {%endfor%}
            </div>
            <div class="col-md-6 col-sm-5">
                <h6>Exclusives</h6>
                {%for exclusive in package.packageservice_set.all%}
                {%if exclusive.is_optional == True%}
                <p><i style="color: red;" class="fa-solid fa-xmark"></i> &nbsp;{{exclusive.service}} - ksh {{exclusive.price}}</p>
                {%endif%}
                {%endfor%}
            </div>
        </div>
    </div>
</div>
</div>
 
{%endblock%}

JVSafaris/JVSafarisMain/templates/jvsafarismain/package.html
{%extends 'JVSafarisMain/base.html'%}

{%load static%}

{%block head%}
<title>Our packages</title>
{%endblock%}

{%block pagetitle%}
Our packages
{%endblock%}

{%block subtitle%}
Our packages
{%endblock%}

{%block body%}
    <!-- Packages Start -->
    <div class="container-fluid py-5">
        <div class="container pt-5 pb-3">
            <div class="text-center mb-3 pb-3">
                <h6 class="text-primary text-uppercase" style="letter-spacing: 5px;">Packages</h6>
                <h1>Perfect Tour Packages</h1>
            </div>
           {%for category in package_categories%}
           {%if category.package_set.count <= 0%}
           <div></div>
           {%else%}
           <h3>{{category.name}}</h3>
          <p>{{category.description}}</p>
           <div class="row">
           {%for package in category.package_set.all%}
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="package-item bg-white mb-2">
                   <a href="{%url 'JVS:package-desc' package.id%}"> <img class="img-fluid" src="{{package.image.url}}" alt=""></a>
                    <div class="p-4">
                        <div class="d-flex justify-content-between mb-3">
                            <small class="m-0"><i class="fa fa-map-marker-alt text-primary mr-2"></i>{{package.destination}}</small>
                            <small class="m-0"><i class="fa fa-calendar-alt text-primary mr-2"></i>{{package.duration}} days</small>
                            <small class="m-0"><i class="fa fa-user text-primary mr-2"></i>{{package.population}} People</small>
                        </div>
                        <a class="h5 text-decoration-none" href="{%url 'JVS:package-desc' package.id%}">{{package.package_name}}</a>
                        <div class="border-top mt-4 pt-4">
                            <div class="d-flex justify-content-between">
                                <h6 class="m-0">{{package.destination.destinantion_name}}</h6>
                                <h5 class="m-0">Kes {{package.price.charge}}</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
           {%endfor%}
        </div>


           {%endif%}
           {%endfor%}
        </div>
    </div>
    <!-- Packages End -->


    <!-- Destination Start -->
    <div class="container-fluid py-5">
        <div class="container pt-5 pb-3">
            <div class="text-center mb-3 pb-3">
                <h6 class="text-primary text-uppercase" style="letter-spacing: 5px;">Destination</h6>
                <h1>Explore Top Destination</h1>
            </div>
            <div class="row">
                {%for destination in destinations%}

                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="destination-item position-relative overflow-hidden mb-2">
                        <img class="img-fluid" src="{{destination.image.url}}" alt="">
                        <a class="destination-overlay text-white text-decoration-none" href="">
                            <h5 class="text-white">{{destination.destinantion_name}}</h5>
                        </a>
                    </div>
                </div>
                {%endfor%}
               
               
               
                
            </div>
        </div>
    </div>
    <!-- Destination Start -->
    {%endblock%}

JVSafaris/JVSafarisMain/templates/jvsafarismain/service detail.html
{%extends 'JVSafarisMain/base.html'%}
{%load static%}

{%block head%}
<title>{{service.item_description}}</title>
{%endblock%}


{%block pagetitle%}
{{service.item_description}}
{%endblock%}

{%block subtitle%}
{{service.item_description}}
{%endblock%}

{%block body%}
<div class="container" style="padding: 10px;">
   <div class="row">
     <div class="col-md-4 col-sm-12">
        <img src="{{service.image.url}}" style="width: 100%;height:100%;" alt="">
     </div>
     <div class="col-md-8 col-sm-6" style="background-color: white;">
        <h2>{{service.item_description}}</h2>
        <div class="row">
            <div class="col-md-5 col-sm-5">

                <p>Cost: <b> Ksh {{service.price.charge}}</b></p>
                <p>Location: {{service.location}}</p>
                <p>Validity:<span style="font-weight: 700;">{{service.price.start_date}} - {{service.price.end_date}}</span></p>

            </div>
            <div class="col-md-6 col-sm-5">
                <p>Duration: <b>{{service.duration}} days</b></p>
                <p>Accommodation: <b>{{service.adults}} adults,{{service.kids}} kids</b></p>
                <p>Category: <b>{{service.category.category_name}}</b></p>
            </div>

        </div>
        <a href="{%url 'JVS:service-booking' service.id%}"><button class="btn btn-primary" style="width: 100%;margin: 5px;">Book Now</button></a>

    </div>
   </div>

   <div class="row" style="background-color: white;margin: 10px 0 10px 0;padding: 10px;">
    <div class="col-md-6 col-sm-12" >
        <h4>Description</h4>
        <p>
           {{service.desc}}
        </p>
    </div>

    <div class="col-md-6 col-sm-12">
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <h6>Inclusives</h6>
            </div>
            <div class="col-md-6 col-sm-5">
                <h6>Exclusives</h6>
            </div>
        </div>
    </div>
</div>

  {%if service.serviceitemgallery_set.count <= 0%}

  <div></div>
  {%else%}
  <div >
    <h4>Gallery</h4>
    <div class="row">
        {%for image in service.serviceitemgallery_set.all%}

        <div class="col-md-4 col-sm-6">
            <img style="width: 100%;padding: 1px;" src="{{image.image.url}}"/>
        </div>
        {%endfor%}

    </div>

  </div>
    {%endif%}
</div>
{%endblock%}

JVSafaris/JVSafarisMain/templates/jvsafarismain/service-categories.html
{%extends 'JVSafarisMain/base.html'%}
{%load static%}


{%block head%}
<title>{{service.category_name}}</title>
{%endblock%}

{%block pagetitle%}
{{service.category_name}}
{%endblock%}

{%block subtitle%}
{{service.category_name}}
{%endblock%}

{%block body%}

<div class="container" style="margin-top: 10px;">
    {%for service in service.service_set.all%}
    {%if service.serviceitem_set.count <= 0%}

    {%else%}
    <h3>{{service.category_description}}</h3>
    <hr>

    {%endif%}
    <div class="row">
    {%for service in service.serviceitem_set.all%}

     <div class="col-lg-4 col-md-6 mb-4">
        <div class="package-item bg-white mb-2">
            <a href="{%url 'JVS:service-detail' service.id %}"><img class="img-fluid" src="{{service.image.url}}" alt=""></a>
            <div class="p-4">
                <div class="d-flex justify-content-between mb-3">
                    <small class="m-0"><i class="fa fa-map-marker-alt text-primary mr-2"></i>{{service.location}}</small>
                    <small class="m-0"><i class="fa fa-user text-primary mr-2"></i>{{service.kids}} kids</small>
                    <small class="m-0"><i class="fa fa-user text-primary mr-2"></i>{{service.adults}} adults</small>
                </div>
                <a class="h5 text-decoration-none" href="">{{service.item_description}}</a>
                <div class="border-top mt-4 pt-4">
                    <div class="d-flex justify-content-between">
                        <h6 class="m-0">{{service.duration}} days</h6>
                        <h5 class="m-0">Kes {{service.price.charge}}</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {%endfor%}
</div>
    {%endfor%}
    
</div>
{%endblock%}